apiVersion: v1
kind: Namespace
metadata:
  name: netology

---

apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    app: hello-world
  namespace: netology
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2

---

apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
  namespace: netology
spec:
  containers:
  - name: echoserver
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2

---

apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  namespace: netology
spec:
  selector:
    app: netology-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
