version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: postgres-container
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1pass
      POSTGRES_DB: user1db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  postgres-data:

