stages:
  - build
  - deploy

image: docker:cli
services:
  - docker:dind

builder:
  stage: build
  script:
    - docker build -t some_local_build:latest .
  except:
    - main

deployer:
  stage: deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY/$CI_PROJECT_PATH/hello:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/hello:gitlab-$CI_COMMIT_SHORT_SHA
  only:
    - main