apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ExternalName
  externalName: rc1a-a3gqf9ui4phlvhu7.mdb.yandexcloud.net 
  ports:
    - name: mysql
      port: 3306
      protocol: TCP

