apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-reader
spec:
  selector:
    matchLabels:
      app: log-reader
  template:
    metadata:
      labels:
        app: log-reader
    spec:
      containers:
      - name: multitool
        image: praqma/network-multitool
        volumeMounts:
        - name: var-log
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: var-log
        hostPath:
          path: /var/log
