---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - role: clickhouse
      clickhouse_version: "22.3.3.44"
      clickhouse_dbs_custom:
        - {name: sample, state: present, }
      clickhouse_users_custom:
        - { name: "loger",
            password: "loger",
            networks: { 192.168.1.81, 192.168.1.79 },
            profile: "default",
            quota: "default",
            dbs: "sample"}

- name: "Install Vector"
  hosts: vector
  roles: 
      - vector-role
- name: "Install Lighthouse"
  hosts: lighthouse  
  roles: 
      - lighthouse
