{
 "title": "My Node Dashboard Alert",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "prometheus", "query": { "query": "label_values(prometheus)" } },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info{prometheus=~\"$prometheus\"}, job)"
    }
   },
   {
    "name": "host",
    "label": "host",
    "query": {
     "query": "label_values(node_uname_info{prometheus=~\"$prometheus\",job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "instance",
    "query": {
     "query": "label_values(node_uname_info{prometheus=~\"$prometheus\",job=~\"$job\",nodename=~\"$host\"},instance)"
    }
   },
   { "name": "interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "show_host",
    "label": "show_host",
    "query": {
     "query": "label_values(node_uname_info{prometheus=~\"$prometheus\",job=~\"$job\",instance=~\"$node\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$job: CPU Used %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[5m])) by (instance) * 100\r\n\r\n\r\n\r",
     "legendFormat": "used%"
    }
   ]
  },
  {
   "title": "$job: Free Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemFree_bytes{job=~\"nodeexporter\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "CPU Loadaverage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_load5{job=\"nodeexporter\"})",
     "legendFormat": "load5"
    },
    {
     "expr": "sum(node_load15{job=\"nodeexporter\"})",
     "legendFormat": "load15"
    },
    {
     "expr": "sum(node_load1{job=\"nodeexporter\"})",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "title": "$job: Free Disk Space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (node_filesystem_free_bytes{instance=\"192.168.1.45:9100\", fstype=~\"ext.*|xfs\", mountpoint=\"/\"} * 100 / node_filesystem_size_bytes{instance=\"192.168.1.45:9100\", fstype=~\"ext.*|xfs\", mountpoint=\"/\"})\r",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}